// Auto-generated by scripts/generate-geo-dataset.mjs - DO NOT EDIT MANUALLY
import type { EnrichedCityGeo } from "@/lib/geo/types";
import rawCities from "./cities.json";

export const ENRICHED_CITIES: EnrichedCityGeo[] = rawCities as EnrichedCityGeo[];

export function getAllEnrichedCities(): EnrichedCityGeo[] {
  return ENRICHED_CITIES;
}

export function getEnrichedCityBySlug(slug: string): EnrichedCityGeo | undefined {
  return ENRICHED_CITIES.find((c) => c.slug === slug);
}

export function getCitiesByCountryCode(countryCode: string): EnrichedCityGeo[] {
  const upper = countryCode.toUpperCase();
  return ENRICHED_CITIES.filter((c) => c.countryCode === upper);
}
