// Auto-generated by scripts/generate-geo-dataset.mjs - DO NOT EDIT MANUALLY
import type { EnrichedCountry } from "@/lib/geo/types";
import rawData from "./countries.json";

export const ENRICHED_COUNTRIES: EnrichedCountry[] = rawData as EnrichedCountry[];

export function getAllCountries(): EnrichedCountry[] {
  return ENRICHED_COUNTRIES;
}

export function getCountryByIso2(iso2: string): EnrichedCountry | undefined {
  const upper = iso2.toUpperCase();
  return ENRICHED_COUNTRIES.find((c) => c.iso2 === upper);
}

export function getCountryByName(name: string): EnrichedCountry | undefined {
  const lower = name.toLowerCase();
  return ENRICHED_COUNTRIES.find((c) => c.name.toLowerCase() === lower);
}
