import type { TripPlan, PersonalizedReminder } from "./types";

/**
 * Formats a Date object into an iCalendar UTC timestamp: YYYYMMDDTHHMMSSZ
 */
function formatIcsDate(date: Date): string {
  return date
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}/, "");
}

/**
 * Escapes text for iCalendar description field according to RFC 5545
 */
function escapeIcsText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

/**
 * Generates an RFC 5545 compliant .ics file containing scheduled security alerts,
 * arrival protocols, and evening heartbeat alarms for the solo traveler's smartphone calendar.
 */
export function generateTripIcs(trip: TripPlan, reminders: PersonalizedReminder[]): string {
  const startDate = new Date(
    `${trip.startDate}T${String(trip.arrivalHour || 14).padStart(2, "0")}:00:00Z`,
  );
  const now = new Date();
  const dtStamp = formatIcsDate(now);

  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//SoloTravelSecurity//Personalized Ingress Calendar 2.0//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    `X-WR-CALNAME:Security Protocol: ${trip.destinationCity}`,
    "X-WR-TIMEZONE:UTC",
  ];

  for (const rem of reminders) {
    // Determine event timestamp based on offset or phase
    const eventDate = new Date(startDate);
    if (rem.calendarOffsetHours !== undefined) {
      eventDate.setHours(eventDate.getHours() + rem.calendarOffsetHours);
    } else if (rem.phase === "pre_trip") {
      eventDate.setDate(eventDate.getDate() - 2);
    } else if (rem.phase === "in_transit") {
      // Keep near start time
    } else if (rem.phase === "in_destination") {
      eventDate.setHours(18, 0, 0, 0); // 18:00 local
    } else if (rem.phase === "post_trip") {
      eventDate.setDate(eventDate.getDate() + 5);
    }

    const eventStart = formatIcsDate(eventDate);
    const endDate = new Date(eventDate.getTime() + 30 * 60 * 1000); // 30-min duration
    const eventEnd = formatIcsDate(endDate);

    const description = [
      `[SECURITY PROTOCOL - ${rem.priority} PRIORITY]`,
      rem.summary,
      "",
      "DIRECTIVE PROTOCOL:",
      ...rem.actionProtocol.map((step, idx) => `${idx + 1}. ${step}`),
      "",
      `Destination: ${trip.destinationCity}, ${trip.destinationCountry}`,
      `Lodging: ${trip.lodgingName || "Primary Lodging"} (${trip.lodgingFloor || "standard floor"})`,
      "Generated by SoloTravelSecurity Field Engine · Offline Safe",
    ].join("\n");

    const uid = `sts-${trip.id}-${rem.id}@solotravelsecurity.com`;

    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${uid}`);
    lines.push(`DTSTAMP:${dtStamp}`);
    lines.push(`DTSTART:${eventStart}`);
    lines.push(`DTEND:${eventEnd}`);
    lines.push(`SUMMARY:🛡️ [${rem.phase.toUpperCase()}] ${rem.title}`);
    lines.push(`DESCRIPTION:${escapeIcsText(description)}`);
    lines.push(`LOCATION:${escapeIcsText(`${trip.destinationCity}, ${trip.destinationCountry}`)}`);
    lines.push("STATUS:CONFIRMED");

    // Add alert alarm 15 minutes before event
    lines.push("BEGIN:VALARM");
    lines.push("ACTION:DISPLAY");
    lines.push(`DESCRIPTION:🛡️ PROTOCOL: ${rem.title}`);
    lines.push("TRIGGER:-PT15M");
    lines.push("END:VALARM");

    lines.push("END:VEVENT");
  }

  lines.push("END:VCALENDAR");

  return lines.join("\r\n");
}
