// Auto-generated by scripts/graphql-emit-documents.mjs - DO NOT EDIT MANUALLY

export const AllCountriesDocument =
  "query AllCountries($region: String, $riskTier: RiskTier, $search: String) {\n  countries(region: $region, riskTier: $riskTier, search: $search) {\n    iso2\n    iso3\n    name\n    nativeName\n    capital\n    currencyCode\n    currencySymbol\n    region\n    defaultRiskTier\n    emergencyNumbers {\n      police\n      ambulance\n      touristPolice\n    }\n    electricalStandards {\n      voltage\n      plugTypes\n    }\n  }\n}";

export const BreadcrumbsForRouteDocument =
  "query BreadcrumbsForRoute($path: String!) {\n  breadcrumbsForRoute(path: $path) {\n    label\n    href\n    position\n  }\n}";

export const ConfirmHeartbeatDocument =
  "mutation ConfirmHeartbeat($token: String!, $milestoneId: String!) {\n  confirmIngressHeartbeat(token: $token, milestoneId: $milestoneId) {\n    token\n    status\n    nextWindowUtc\n    milestones {\n      id\n      label\n      expectedTime\n      completedTime\n      status\n    }\n  }\n}";

export const CountryByIso2Document =
  "query CountryByIso2($iso2: ID!) {\n  country(iso2: $iso2) {\n    iso2\n    iso3\n    name\n    nativeName\n    capital\n    currencyCode\n    currencySymbol\n    currencyName\n    phonePrefix\n    region\n    subregion\n    wikidataId\n    coordinates {\n      latitude\n      longitude\n    }\n    defaultRiskTier\n    emergencyNumbers {\n      police\n      ambulance\n      fire\n      touristPolice\n    }\n    consularHotlines {\n      usEmbassyPhone\n      ukEmbassyPhone\n      ausEmbassyPhone\n    }\n    electricalStandards {\n      voltage\n      frequency\n      plugTypes\n    }\n    overview\n    keySafetyRules\n    primaryCities {\n      slug\n      name\n      primaryAirportCode\n      riskTier\n    }\n  }\n}";

export const DecisionTablesDocument =
  "query DecisionTables {\n  decisionTables {\n    id\n    title\n    description\n    pillarId\n    conditionColumns {\n      key\n      label\n      type\n      allowedValues\n      unit\n    }\n    actionColumns {\n      key\n      label\n      type\n    }\n    rules {\n      ruleId\n      scenario\n      priority\n      conditions\n      actions\n    }\n    defaultAction\n  }\n}";

export const GenerateChecklistDocument =
  "query GenerateChecklist($input: GenerateChecklistInput) {\n  generateChecklist(input: $input) {\n    generatedAt\n    totalItems\n    criticalCount\n    spofCount\n    items {\n      id\n      title\n      description\n      pillarId\n      phaseId\n      criticality\n      isSPOF\n      verificationType\n      applicableArchetypes\n      minimumRiskTier\n      decisionTableRef\n      truthTableRef\n      scoringDeductionPoints\n      recommendedGearSkus\n    }\n    byPillar {\n      id\n      name\n      slug\n      items {\n        id\n        title\n        criticality\n        isSPOF\n        scoringDeductionPoints\n      }\n    }\n    byPhase {\n      id\n      name\n      slug\n      items {\n        id\n        title\n        criticality\n        isSPOF\n        scoringDeductionPoints\n      }\n    }\n  }\n}";

export const GuardianPortalDocument =
  "query GuardianPortal($token: ID!) {\n  guardianPortal(token: $token) {\n    token\n    travelerName\n    destinationCity\n    destinationCountry\n    status\n    nextWindowUtc\n    readinessScore\n    readinessGrade\n    milestones {\n      id\n      label\n      expectedTime\n      completedTime\n      status\n    }\n    consularHotlines {\n      usEmbassyPhone\n      ukEmbassyPhone\n      ausEmbassyPhone\n    }\n    emergencyNumbers {\n      police\n      ambulance\n      fire\n      touristPolice\n    }\n  }\n}";

export const MatchedProductsDocument =
  "query MatchedProducts($context: SituationalContextInput!) {\n  matchedProducts(context: $context) {\n    sku\n    name\n    category\n    howToRole\n    priorityRank\n    situationalRationale\n    isPrimaryRecommendation\n    price\n    priceCurrency\n    affiliateUrl\n    brand\n    author\n    isbn\n    ratingValue\n    ratingCount\n    pros\n    cons\n  }\n}";

export const RemoveFavoriteDocument =
  "mutation RemoveFavorite($sessionToken: String!, $itemId: ID!) {\n  removeFavorite(sessionToken: $sessionToken, itemId: $itemId)\n}";

export const SaveFavoriteDocument =
  "mutation SaveFavorite($sessionToken: String!, $item: FavoriteItemInput!) {\n  saveFavorite(sessionToken: $sessionToken, item: $item) {\n    id\n    type\n    title\n    url\n    category\n    description\n    price\n    rating\n    badge\n    savedAt\n    notes\n  }\n}";

export const SearchFacetedItemsDocument =
  "query SearchFacetedItems($filter: FacetedSearchFilterInput) {\n  searchFacetedItems(filter: $filter) {\n    totalCount\n    items {\n      id\n      title\n      slug\n      url\n      type\n      category\n      categoryLabel\n      description\n      tagline\n      format\n      priceTier\n      priceFormatted\n      rating\n      ratingCount\n      affiliateUrl\n      keyHighlight\n    }\n    facetCounts {\n      types {\n        value\n        label\n        count\n      }\n      categories {\n        value\n        label\n        count\n      }\n      formats {\n        value\n        label\n        count\n      }\n      priceTiers {\n        value\n        label\n        count\n      }\n      riskTiers {\n        value\n        label\n        count\n      }\n    }\n  }\n}";

export const SecurityTruthTablesDocument =
  "query SecurityTruthTables {\n  truthTables {\n    id\n    title\n    description\n    scenarioCategory\n    propositions {\n      symbol\n      key\n      name\n      description\n    }\n    rows {\n      rowId\n      inputs\n      outputs\n      formalRationale\n    }\n    completenessVerified\n  }\n}";

export const TaxonomyTreeDocument =
  "query TaxonomyTree {\n  securityPillars {\n    id\n    name\n    slug\n    description\n    weight\n    icon\n    primaryDirectives\n  }\n  lifecyclePhases {\n    id\n    name\n    slug\n    order\n    description\n    typicalWindow\n  }\n}";

export const UserFavoritesDocument =
  "query UserFavorites($sessionToken: String!) {\n  userFavorites(sessionToken: $sessionToken) {\n    id\n    type\n    title\n    url\n    category\n    description\n    price\n    rating\n    badge\n    savedAt\n    notes\n  }\n}";
